export const keywords = [
  "Event ticketing platform",
  "Buy event tickets online",
  "All-in ticketing",
  "Best ticket platform in Nigeria",
  "Ticket sales by All-in",
  "Event check-in solutions",
  "Online ticketing for events",
  "Efficient ticketing system",
  "Startup in Port Harcourt",
  "Best event platform in Nigeria",
  "All-in Technologies",
  "Nigeria event tickets",
  "Port Harcourt events",
  "Ticketing for concerts",
  "Event management system",
  "Seamless ticket sales",
  "All-in event solutions",
  "Digital ticketing platform",
];
